version: "3.7"
services:
  server:
    image: duckulus/untis-bot
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    volumes:
      - ./apps/server/.wwebjs_auth:/app/apps/server/.wwebjs_auth
      - ./packages/database/prisma:/app/packages/database/prisma
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10