version: "3"
services:
  server:
    image: duckulus/untis-bot
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    volumes:
      - ./apps/server/.wwebjs_auth:/app/apps/server/.wwebjs_auth
      - ./packages/db/prisma:/app/packages/db/prisma
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
